name: boni_ilsstandardizenonoiserefit

init:
  _target_: src.optim.VanillaBO

  model_class:
    _target_: hydra.utils.get_class
    path: src.models.HeuristicNoiseInjectionGP

  model_kwargs:
    outcome_transform: null
    initial_injection: "no_noise"
    heuristic_algorithm: "ils_mll"
    refit_gp: true
    heuristic_hyperparameters:
      perturbation_size: 0.2

  preprocessing_transform:
    _target_: src.transformations.StandardizeTransform

  acqf_class:
    _target_: hydra.utils.get_class
    path: botorch.acquisition.${acquisition.package}.${acquisition.acquisition_func}

  acqf_kwargs: ${acquisition.acqf_kwargs}

  verbose: true
