name: boni_plain

init:
  _target_: src.optim.VanillaBO

  model_class:
    _target_: hydra.utils.get_class
    path: src.models.HeuristicNoiseInjectionGP

  model_kwargs:
    outcome_transform: null
    initial_injection: "noise"
    heuristic_algorithm: "naive_mll"
    
  acqf_class:
    _target_: hydra.utils.get_class
    path: botorch.acquisition.${acquisition.package}.${acquisition.acquisition_func}

  acqf_kwargs: ${acquisition.acqf_kwargs}

  verbose: true