name: turboni_trbsnorm

init:
  _target_: src.optim.TrustRegionBO

  model_class:
    _target_: hydra.utils.get_class
    path: src.models.TrustRegionNoiseInjectionBeamSearchGP

  model_kwargs:
    outcome_transform: null
    beam_width: 10  # Number of beam search candidates
    normalize_noise: true

  preprocessing_transform:
    _target_: src.transformations.StandardizeTransform

  acqf_class:
    _target_: hydra.utils.get_class
    path: botorch.acquisition.${acquisition.package}.${acquisition.acquisition_func}

  acqf_kwargs: ${acquisition.acqf_kwargs}

  verbose: true
