defaults:
  - _self_
  - objective: branin
  - optimizer: bo_plain
  - path: local
  - acquisition: ucb

sweep_name: "final"
suffix: "" #${now:%Y-%m-%d_%H-%M}
seed: 0 # Seed for reproducibility
mode: base

name: ${optimizer.name}_${objective.name}_${objective.dim}_${acquisition.acquisition_func}${suffix}_${seed}

save_dir: ${path.base_path}/results/${sweep_name}/${name}
verbose_level: ${path.verbose_level}

hydra:
  run:
    dir: ${path.base_path}/outputs/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${path.base_path}/outputs/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}